add df collector
gently-whitesnow/rat pull request #1
Opened 2023-09-09 22:27 UTC by gently-whitesnow

2023-09-09 22:30 UTC, gently-whitesnow commented on src/core/worker/worker.cpp
> +            if(dtoResult.IsReady()) _models.push_back(std::move(dtoResult));
Теперь в отправители передается результат, а не модель, чтобы отправители могли также реагировать на ошибки и слать их

2023-09-09 22:31 UTC, gently-whitesnow commented on src/data_access/collectors/collector.cpp
> +    _lastCollectionTime = std::chrono::system_clock::now();
Теперь за время отвечает класс родитель, в специализированных коллекторах достаточно только реализовывать логику, не задумываясь о частоте вызова

2023-09-09 22:35 UTC, gently-whitesnow commented
Добавил коллектор 'df -h' с возможностью фильтрации по дискам

2023-09-10 00:31 UTC, oneofthemoons requested changes
Код не такое говно, а автор не совсем лох, но нужно поработать еще

2023-09-10 00:31 UTC, oneofthemoons commented on src/data_access/collectors/collector.cpp
> +    _lastCollectionTime = std::chrono::system_clock::now() -
Почему здесь из текущего времени вычитается интервал?

2023-09-10 00:31 UTC, oneofthemoons commented on src/data_access/collectors/collector.cpp
> +    _lastCollectionTime = std::chrono::system_clock::now();
Только родитель — теперь точно не интерфейс, а полноценный класс со сложной логикой внутри, стоит поменять нейминг

2023-09-10 00:31 UTC, oneofthemoons commented on src/data_access/collectors/unix/df_collector/df_collector.cpp
> +    std::string subStreamString = "";
Ну наверное это просто line

2023-09-10 00:31 UTC, oneofthemoons commented on src/data_access/collectors/unix/df_collector/df_collector.cpp
> +            if (isFirstLine) {
Обработай первую строку отдельно, чтобы не делать лишних действий n раз

2023-09-10 00:31 UTC, oneofthemoons commented on src/data_access/collectors/unix/df_collector/df_collector.cpp
> +    while (std::getline(rawStringStream, subStreamString, '\n')) {
delimeter указывать не обязательно

2023-09-10 00:31 UTC, oneofthemoons commented on src/data_access/collectors/unix/df_collector/df_collector.cpp
> +                filteredString += "\n" + subStreamString;
Чисто перфоманс комментарий - вместо пушинга в стрингу (а она кстати может быть очень большой), лучше написать сплиттинг строки на массив string_view и потом пройтись по нему через remove_if в стиле
auto vec = Split(rawString);
vec.resize(std::distance(vec.begin(), std::remove_if(vec.begin(), vec.end(), [](std::string_view str) { return !str.starts_with(disc_name);});
В конце ты сможешь через reduce посчитать общую длину всех отфильтрованных вхождений и за одну крупную аллокацию сформировать filteredString.

2023-09-10 00:31 UTC, oneofthemoons commented on src/data_access/collectors/unix/df_collector/df_collector.h
> +    DfCollector(int collectionSecondsInterval, std::string collectorName,
int? Пишу -100 - что получаю? Компилер даже не поругается, используй chrono или хотябы uint32_t

2023-09-10 00:31 UTC, oneofthemoons commented on src/data_access/collectors/unix/df_collector/df_collector.h
> +    DfCollector(int collectionSecondsInterval, std::string collectorName);
the same

2023-09-10 00:31 UTC, oneofthemoons commented on src/data_access/collectors/unix/df_collector/df_collector.h
> +    DfCollector(int collectionSecondsInterval, std::string collectorName,
почему стринга передается по значению? Если не привык к ссылкам, используй std::string_view

2023-09-10 00:31 UTC, oneofthemoons commented on src/data_access/collectors/unix/system_executor.cpp
> +    std::string output = "";
= "" не имеет смысла, а стек засран

2023-09-10 00:31 UTC, oneofthemoons commented on src/data_access/collectors/unix/system_executor.cpp
> +    if (output.empty()) {
empty output - вообще не обязательно ошибка, ошибку нужно отлавливать по ret-code и errno в вызовх popen, fgets и pclose

2023-09-10 00:31 UTC, oneofthemoons commented on src/data_access/collectors/unix/system_executor.cpp
> +    return Result<std::string>(std::move(output));
std::move здесь будет подставлен компилятором при -O2 и выше (дефолт - O2), <std::string> тоже

2023-09-10 00:31 UTC, oneofthemoons commented on src/main.cpp
>      collectors.push_back(std::move(exampleCollector));
emplace_back лучше чем push_back почти всегда

2023-09-10 00:31 UTC, oneofthemoons commented on src/models/dto.h
> +    std::string _data;
Это поле делает интерфейс не интерфейсом хотя бы потому, что ответственность за его заполнение кажется вообще не определена какими-либо методами, да и вообще филд приватный - как он наследуется то?)

2023-09-10 00:31 UTC, oneofthemoons commented on src/models/result.h
> +template <typename TValue>
TValue ничем не понятнее, чем просто T в этом контексте. T при этом - вполне признанный стандарт.

2023-09-10 00:31 UTC, oneofthemoons commented on src/models/result.h
>  class Result {
Эта реализация Result в целом странная - много лишней памяти и отстутвие возможности конфигурировать тип ошибки. Подумай, возможно, тебе стоит реализовать его через std::variant, пользовательские типы TOk и TError, сейчас это выглядит не как Result, а как ResultForMyFeature.

2023-09-10 00:31 UTC, oneofthemoons commented on src/models/result_status.h
> +enum ResultStatus { Success, NotReady, InternalError };
enum class

2023-09-10 00:31 UTC, oneofthemoons commented on src/data_access/collectors/collector.cpp
> +    _lastCollectionTime = std::chrono::system_clock::now() -
Выглядит как магия-код, отсюда и вопрос. Если есть обоснование, пусть код его документирует любым доступным образом

2023-09-10 00:31 UTC, oneofthemoons commented on src/data_access/collectors/unix/system_executor.cpp
> +    std::string output = "";
А это два байта, живущие весь цикл работы программы. Вспомни, насколько они ценны, когда сервак стоит 130 рублей в месяц.

2023-09-10 08:05 UTC, gently-whitesnow commented on src/data_access/collectors/collector.cpp
> +    _lastCollectionTime = std::chrono::system_clock::now() -
допустим интервал сбора 15 секунд.
Запускаю программу, жду 15 секунд для сбора, если указываю std::chrono::system_clock::now()
Чтобы не ждать, а начать сбор при запуске вычитаются эти 15 секунд при инициализации

2023-09-10 10:59 UTC, baryon-asymm commented on src/models/result_status.h
> +enum class ResultStatus { Success, NotReady, InternalError };
Не понимаю смысл ResultStatus::NotReady

2023-09-10 11:06 UTC, merged